### ISSUE TITLE
查看任务运行状态和停止任务问题

### ISSUE THREAD

**Issue by helinwei** [392223903/EasyTask#1]
1、一个任务启动多次，task_status只能查询出某次启动的任务列表；
2、停止任务时，不可以指定ppid或者任务名称停止。
请问如何解决呢

**Comment by thinker-gao** [comment]
不好意思哈，这个之前想搞的 ，但是担心依赖比较多  建议用linux命令来处理   ps  aux|grep 任务名

**Comment by thinker-gao** [comment]
通过上面的命令找到进程id  然后进行kill  ，后期会加上您的建议。

**Comment by thinker-gao** [comment]
最新版本已经修改为 启动不会生成多个多次进程，每次启动后之前启动的都将会被停止。关于单个停止任务的请看最新的文档说明
